name: My GitHub Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
    
    - name: Install dependencies
      run: npm intsall
      
    - name: Build web bundle
      run: npm run build

    # Add more steps here as needed based on your workflow requirements
